# Generated by Django 5.1.1 on 2024-10-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="account",
            options={"ordering": ["-date_opened"]},
        ),
        migrations.AlterField(
            model_name="account",
            name="account_type",
            field=models.CharField(
                choices=[("savings", "Savings"), ("current", "Current")],
                db_index=True,
                default="savings",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="balance",
            field=models.DecimalField(
                db_index=True, decimal_places=2, default=10000.0, max_digits=15
            ),
        ),
    ]
