# Generated by Django 5.1.1 on 2024-10-07 03:38

import pyotp
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="otp_secret",
            field=models.CharField(default=pyotp.random_base32, max_length=255),
        ),
    ]
